import Head from "next/head";
import { api } from "~/utils/api";

export default function Home() {
  const { data } = api.city.getAll.useQuery();

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          <h1>Addresses</h1>
          {data?.map((city) => (<div key={city.id}>{city.name}</div>))}
        </div>
      </main>
    </>
  );
}
