import React from "react";
import Head from "next/head";
import { api } from "~/utils/api";
import {
  ComboBox,
  Input,
  Item,
  Label,
  ListBox,
  Popover,
} from "react-aria-components";

export default function Home() {
  const { data } = api.city.getAll.useQuery();
  /* const data = [
    { id: 0, name: "Bergen" },
    { id: 1, name: "Trondheim" },
    { id: 2, name: "Oslo" },
    { id: 3, name: "Stavanger" },
  ]; */

  const [majorId, setMajorId] = React.useState<React.Key | null>(null);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div>
          <p>Selected topic id: {majorId}</p>
          <ComboBox defaultItems={data} onSelectionChange={setMajorId}>
            <Label>Address</Label>
            <div>
              <Input />
            </div>
            <Popover>
              <ListBox>
                {data?.map((city) => (
                  <Item key={city.id}>{city.name}</Item>
                ))}
              </ListBox>
            </Popover>
          </ComboBox>
        </div>
      </main>
    </>
  );
}
