import React from "react";
import Head from "next/head";
import Link from "next/link";

interface LayoutProps {
  children: React.ReactNode;
}

export default function Layout({ children }: LayoutProps) {
  const cities = ["Bergen", "Oslo", "Trondheim", "Stavanger"];
  return (
    <>
      <Head>
        <title>finnbydel</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center gap-4  bg-slate-900 text-white">
        <h1 className="text-5xl">Finn bydelen din</h1>
        <p className="text-3xl">
          Usikker på hvilken bydel du bor i? Lurer du på hvilken bydel en
          adresse tilhører? Søk på adresser her.
        </p>
        <p className="text-3xl">Hvilken by ligger adressen i?</p>
        <ul>
          {cities.map((city, i) => (
            <li key={i} className="text-3xl">
              <Link href={city.toLowerCase()}>{city}</Link>
            </li>
          ))}
        </ul>
        {children}
      </main>
    </>
  );
}
